### ISSUE TITLE
課題　相関係数の実装

### ISSUE THREAD

**Issue by xianshiyuming** [SengokuLAB/FirstStep#2]
下の表は, 10人の生徒に10点満点の2種類のテスト A,Bを行った結果 である。次の値を`Pandasを用いた場合` と`用いない場合` の２パターンで求めよ。ただし,得られた値が無限小数の場合は,小数第2 位を四捨五入せよ。 

生徒の番号 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10
------------- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- 
テストAの得点 | 2 | 9 | 4 | 7 | 1 | 5 | 8 | 3 | 6 | 5
テストBの得点 | 1 | 5 | 3 | 8 | 2 | 6 | 7 | 4 | 5 | 9

(1) テストAの得点の平均値
(2) テストBの得点の分散
(3) テストAとテストBの得点の共分散
(4) テストAとテストBの得点の相関係数

**Comment by ghost** [comment]
@xianshiyuming お疲れ様です。課題をpushしたいのですがリモートリポジトリのクローンができないです。ipynbファイルをFirstStep/2019にアップロードする形でもよいのでしょうか。

**Comment by ghost** [comment]
@xianshiyuming 最終課題を提出しました。チェックお願いします。

**Comment by xianshiyuming** [comment]
@Takahashi-Tetsuya お疲れ様です。レス遅くなってすみません、pushしてもらったファイルがipynbファイルではないでようです。もう一度ご確認いただけますか？

難しい場合にはご連絡ください！

**Comment by ghost** [comment]
@xianshiyuming 拡張子を直してアップロードしてみたのですが、github上でアップロードしたファイルを開けなくなってしまいます。どこを直したら良いでしょうか。

**Comment by ghost** [comment]
@xianshiyuming お疲れ様です。課題のプッシュができない件についてですが、コマンドラインツールをインストールしたらプッシュできました。corr_coefというファイル名でプッシュしました。チェックよろしくお願いします。

**Comment by xianshiyuming** [comment]
自力でできたようでよかったです！

**Comment by xianshiyuming** [comment]
@Takahashi-Tetsuya 拝見しました、こちらの内容でバッチリです！別途ご連絡しますね、おつかれさまでした！
